Repository openshift/multi-operator-manager, pull requests merged in 2024-10, with the labels that each got.

#7 API-1835: Update README.md and OWNERS
  OWNERS
  README.md
Labels: lgtm, approved, jira/valid-reference, no-qe

#10 API-1835: heavy refactor to use library-go and make downstream command building easier
  go.mod
  go.sum
  pkg/applyconfiguration/README.md
  pkg/applyconfiguration/equivalence.go
  pkg/applyconfiguration/execer.go
  pkg/applyconfiguration/result.go
  pkg/cmd/multi-operator-manager/sample-operator/apply-configuration/apply_configuration_command.go
  pkg/library/libraryapplyconfiguration/README.md
  pkg/library/libraryapplyconfiguration/apply_configuration.go
  pkg/library/libraryapplyconfiguration/client_mutations.go
  pkg/library/libraryapplyconfiguration/command.go
  pkg/library/libraryapplyconfiguration/directory_apply_configuration.go
  pkg/library/libraryapplyconfiguration/directory_mutations.go
  pkg/library/libraryapplyconfiguration/equivalence.go
  pkg/library/libraryapplyconfiguration/options.go
  pkg/library/libraryapplyconfiguration/simple.go
  pkg/library/libraryapplyconfiguration/write.go
  pkg/library/librarydependson/prune_mustgather.go
  pkg/library/librarydependson/prune_mustgather_test.go
  pkg/library/librarydependson/resource.go
  pkg/sampleoperator/sampleapplyconfiguration/sample_apply_configuration.go
  pkg/test/testapplyconfiguration/tester.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/mutation_tracker.go
  vendor/modules.txt
Labels: approved, jira/valid-reference

#11 NO-JIRA: sample operator adjustment
  pkg/cmd/multi-operator-manager/sample-operator/apply-configuration/apply_configuration_command.go
  pkg/library/libraryapplyconfiguration/command.go
  pkg/library/libraryapplyconfiguration/write.go
  pkg/sampleoperator/sampleapplyconfiguration/sample_apply_configuration.go
Labels: lgtm, approved, jira/valid-reference

#13 NO-JIRA: don't wait for operator sync when running in controller mode
  pkg/library/libraryapplyconfiguration/operator_launch_helpers.go
Labels: lgtm, approved, jira/valid-reference

#15 API-1835: write output even when there are errors
  pkg/library/libraryapplyconfiguration/options.go
Labels: lgtm, approved, jira/valid-reference

#17 API-1835: add input-resources command
  go.mod
  go.sum
  pkg/cmd/multi-operator-manager/sample-operator/inputresources/input_resources_command.go
  pkg/cmd/multi-operator-manager/sample-operator/sample_operator_command.go
  pkg/library/libraryinputresources/command.go
  pkg/library/libraryinputresources/easy_creation.go
  pkg/library/libraryinputresources/options.go
  pkg/library/libraryinputresources/options_test.go
  pkg/library/libraryinputresources/prune_mustgather.go
  pkg/library/libraryinputresources/prune_mustgather_test.go
  pkg/library/libraryinputresources/test-data/anded-indirect-references-01/expected-output/namespaces/openshift-config/core/secrets.yaml
  pkg/library/libraryinputresources/test-data/anded-indirect-references-01/input-dir/cluster-scoped-resources/config.openshift.io/ingresses.yaml
  pkg/library/libraryinputresources/test-data/anded-indirect-references-01/input-dir/namespaces/openshift-config/core/secrets.yaml
  pkg/library/libraryinputresources/test-data/anded-indirect-references-01/input-resources.yaml
  pkg/library/libraryinputresources/test-data/direct-references-01/input-resources.yaml
  pkg/library/libraryinputresources/test-data/indirect-references-01/input-resources.yaml
  pkg/library/libraryinputresources/types.go
  pkg/library/libraryoutputresources/easy_creation.go
  pkg/library/libraryoutputresources/types.go
  pkg/sampleoperator/sampleinputresources/sample_input_resources.go
  pkg/sampleoperator/sampleoutputresources/sample_output_resources.go
  vendor/github.com/PaesslerAG/gval/.gitignore
  vendor/github.com/PaesslerAG/gval/.travis.yml
  vendor/github.com/PaesslerAG/gval/LICENSE
  vendor/github.com/PaesslerAG/gval/README.md
  vendor/github.com/PaesslerAG/gval/evaluable.go
  vendor/github.com/PaesslerAG/gval/functions.go
  vendor/github.com/PaesslerAG/gval/gval.go
  vendor/github.com/PaesslerAG/gval/language.go
  vendor/github.com/PaesslerAG/gval/operator.go
  vendor/github.com/PaesslerAG/gval/parse.go
  vendor/github.com/PaesslerAG/gval/parser.go
  vendor/github.com/PaesslerAG/gval/prtg-batmin-gopher.png
  vendor/github.com/PaesslerAG/jsonpath/.gitignore
  vendor/github.com/PaesslerAG/jsonpath/.travis.yml
  vendor/github.com/PaesslerAG/jsonpath/LICENSE
  vendor/github.com/PaesslerAG/jsonpath/README.md
  vendor/github.com/PaesslerAG/jsonpath/jsonpath.go
  vendor/github.com/PaesslerAG/jsonpath/parse.go
  vendor/github.com/PaesslerAG/jsonpath/path.go
  vendor/github.com/PaesslerAG/jsonpath/placeholder.go
  vendor/github.com/PaesslerAG/jsonpath/selector.go
  vendor/github.com/PaesslerAG/jsonpath/test.sh
  vendor/github.com/shopspring/decimal/.gitignore
  vendor/github.com/shopspring/decimal/.travis.yml
  vendor/github.com/shopspring/decimal/CHANGELOG.md
  vendor/github.com/shopspring/decimal/LICENSE
  vendor/github.com/shopspring/decimal/README.md
  vendor/github.com/shopspring/decimal/decimal-go.go
  vendor/github.com/shopspring/decimal/decimal.go
  vendor/github.com/shopspring/decimal/rounding.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#20 API-1835: sampleoperator: fix resource and kind for the operator client
  pkg/sampleoperator/sampleapplyconfiguration/sample_apply_configuration.go
  test-data/apply-configuration/test-basic-call/expected-output/Configuration/ApplyStatus/cluster-scoped-resources/operator.openshift.io/authentications/001-body-cluster.yaml
  test-data/apply-configuration/test-basic-call/expected-output/Configuration/ApplyStatus/cluster-scoped-resources/operator.openshift.io/authentications/001-options-cluster.yaml
  test-data/apply-configuration/test-basic-call/expected-output/Management/ApplyStatus/cluster-scoped-resources/operator.openshift.io/authentications/001-body-cluster.yaml
  test-data/apply-configuration/test-basic-call/expected-output/Management/ApplyStatus/cluster-scoped-resources/operator.openshift.io/authentications/001-options-cluster.yaml
  test-data/apply-configuration/test-basic-call/expected-output/UserWorkload/ApplyStatus/cluster-scoped-resources/operator.openshift.io/authentications/001-body-cluster.yaml
  test-data/apply-configuration/test-basic-call/expected-output/UserWorkload/ApplyStatus/cluster-scoped-resources/operator.openshift.io/authentications/001-options-cluster.yaml
  test-data/apply-configuration/test-basic-call/input-dir/cluster-scoped-resources/operator.openshift.io/authentications.yaml
Labels: lgtm, approved, jira/valid-reference

#16 API-1835: separate mutations into proper targets based on output-resources
  Makefile
  go.mod
  go.sum
  hack/test-operator-integration.sh
  pkg/cmd/multi-operator-manager/sample-operator/apply-configuration/apply_configuration_command.go
  pkg/library/libraryapplyconfiguration/apply_configuration.go
  pkg/library/libraryapplyconfiguration/client_mutations.go
  pkg/library/libraryapplyconfiguration/client_mutations_test.go
  pkg/library/libraryapplyconfiguration/command.go
  pkg/library/libraryapplyconfiguration/directory_mutations.go
  pkg/library/libraryapplyconfiguration/equivalence.go
  pkg/library/libraryapplyconfiguration/options.go
  pkg/sampleoperator/sampleapplyconfiguration/sample_apply_configuration.go
  pkg/sampleoperator/sampleoutputresources/sample_output_resources.go
  test-data/apply-configuration/test-basic-call/expected-output/Configuration/ApplyStatus/cluster-scoped-resources/operator.openshift.io/authentications/001-body-cluster.yaml
  test-data/apply-configuration/test-basic-call/expected-output/Configuration/ApplyStatus/cluster-scoped-resources/operator.openshift.io/authentications/001-options-cluster.yaml
  test-data/apply-configuration/test-basic-call/expected-output/Configuration/Create/cluster-scoped-resources/config.openshift.io/ingresses/002-body-cluster.yaml
  test-data/apply-configuration/test-basic-call/expected-output/UserWorkload/ApplyStatus/cluster-scoped-resources/operator.openshift.io/authentications/001-body-cluster.yaml
  test-data/apply-configuration/test-basic-call/expected-output/UserWorkload/ApplyStatus/cluster-scoped-resources/operator.openshift.io/authentications/001-options-cluster.yaml
  test-data/apply-configuration/test-basic-call/input-dir/aggregated-discovery-api.yaml
  test-data/apply-configuration/test-basic-call/input-dir/aggregated-discovery-apis.yaml
  test-data/apply-configuration/test-basic-call/input-dir/namespaces/kube-system/core/secrets.yaml
  vendor/github.com/openshift/library-go/pkg/apiserver/jsonpatch/jsonpatch.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/default-discovery/README.md
  vendor/github.com/openshift/library-go/pkg/manifestclient/default-discovery/aggregated-discovery-api.yaml
  vendor/github.com/openshift/library-go/pkg/manifestclient/default-discovery/aggregated-discovery-apis.yaml
  vendor/github.com/openshift/library-go/pkg/manifestclient/get.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/group_resource_discovery.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/list.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/mutation_directory_reader.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/mutation_tracker.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/read_roundtripper.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/serialized_request.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/write_roundtripper.go
  vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_operator_client.go
  vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/object_merger.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/admission.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#22 API-1835: libraryapplycfg: store the controller name alongside the RunOnce func
  go.mod
  go.sum
  pkg/library/libraryapplyconfiguration/operator_launch_helpers.go
  pkg/sampleoperator/sampleapplyconfiguration/sample_apply_configuration.go
  test-data/apply-configuration/test-basic-call/expected-output/Configuration/Create/cluster-scoped-resources/config.openshift.io/ingresses/002-body-cluster.yaml
  test-data/apply-configuration/test-basic-call/expected-output/Management/ApplyStatus/cluster-scoped-resources/operator.openshift.io/authentications/001-body-cluster.yaml
  test-data/apply-configuration/test-forced-error/expected-output/Configuration/Create/cluster-scoped-resources/config.openshift.io/ingresses/002-body-cluster.yaml
  test-data/apply-configuration/test-forced-error/expected-output/Management/ApplyStatus/cluster-scoped-resources/operator.openshift.io/authentications/001-body-cluster.yaml
  vendor/github.com/openshift/library-go/pkg/manifestclient/context.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/group_resource_discovery.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/list.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/mutation_directory_reader.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/mutation_tracker.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/write_roundtripper.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#23 API-1835: save the unspecified resources for inspection
  pkg/library/libraryapplyconfiguration/apply_configuration.go
  pkg/library/libraryapplyconfiguration/options.go
Labels: lgtm, approved, jira/valid-reference

#28 API-1835: ability to run requested controllers
  pkg/applyconfiguration/execer.go
  pkg/library/libraryapplyconfiguration/command.go
  pkg/library/libraryapplyconfiguration/operator_launch_helpers.go
  pkg/sampleoperator/sampleapplyconfiguration/sample_apply_configuration.go
  pkg/test/testapplyconfiguration/tester.go
  pkg/test/testapplyconfiguration/types.go
  test-data/apply-configuration/test-controller-name/expected-output/Configuration/Create/cluster-scoped-resources/config.openshift.io/ingresses/002-body-cluster.yaml
  test-data/apply-configuration/test-controller-name/input-dir/cluster-scoped-resources/operator.openshift.io/authentications.yaml
  test-data/apply-configuration/test-controller-name/input-dir/namespaces/kube-system/core/configmaps.yaml
  test-data/apply-configuration/test-controller-name/input-dir/namespaces/kube-system/core/secrets.yaml
  test-data/apply-configuration/test-controller-name/test.yaml
Labels: lgtm, approved, jira/valid-reference

#29 API-1835: automatically add output-resources to our input-resources
  pkg/cmd/multi-operator-manager/sample-operator/inputresources/input_resources_command.go
  pkg/library/libraryinputresources/command.go
  pkg/library/libraryinputresources/options.go
  pkg/library/libraryinputresources/types.go
  pkg/library/libraryinputresources/validation.go
  pkg/library/libraryoutputresources/easy_creation.go
  pkg/library/libraryoutputresources/types.go
  pkg/sampleoperator/sampleoutputresources/sample_output_resources.go
Labels: lgtm, approved, jira/valid-reference

#34 API-1835: sampleoperator: demo controller
  pkg/sampleoperator/sampleapplyconfiguration/controllers.go
  pkg/sampleoperator/sampleapplyconfiguration/sample_apply_configuration.go
  pkg/sampleoperator/sampleinputresources/sample_input_resources.go
  pkg/sampleoperator/sampleoutputresources/sample_output_resources.go
  test-data/apply-configuration/eventing-01/expected-output/UserWorkload/Create/namespaces/openshift-authentication/core/configmaps/004-body-foo.yaml
  test-data/apply-configuration/test-basic-call/expected-output/UserWorkload/Create/namespaces/openshift-authentication/core/configmaps/004-body-foo.yaml
  test-data/apply-configuration/test-forced-error/expected-output/UserWorkload/Create/namespaces/openshift-authentication/core/configmaps/004-body-foo.yaml
Labels: lgtm, approved, jira/valid-reference

#33 NO-JIRA: use artifact dir for CI output
  hack/test-operator-integration.sh
Labels: lgtm, approved, jira/valid-reference
